server:
  port: 8240

spring:
  application:
    name: crediya
  jackson:
    property-naming-strategy: SNAKE_CASE
  devtools:
    add-properties: false
  r2dbc:
    url: ${SPRING_DATASOURCE_URL:r2dbc:postgresql://localhost:5433/crediYa}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1234@}
    pool:
      enabled: true
      initial-size: 5
      max-size: 20

logging:
  level:
    root: INFO
    com.hiri.crediya: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8240,http://localhost:8241"

auth:
  service:
    url: ${AUTH_SERVICE_URL:http://localhost:8242}